package utils;

import auth.Login;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import database.Connect;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class Processing extends javax.swing.JFrame {

    Connection conn = null;

    public Processing() {
        initComponents();
        conn = Connect.dbConnector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelSystemName = new javax.swing.JLabel();
        jLabelInstructions = new javax.swing.JLabel();
        jLabelRegno = new javax.swing.JLabel();
        txtRegNo = new javax.swing.JTextField();
        jLabelCourseCode = new javax.swing.JLabel();
        txtCourseCode = new javax.swing.JTextField();
        jLabelYrOfEntry = new javax.swing.JLabel();
        txtYrOfEntry = new javax.swing.JTextField();
        jLabelYrsTitle = new javax.swing.JLabel();
        jLabelYrStart = new javax.swing.JLabel();
        txtYrStart = new javax.swing.JTextField();
        jLabelSemEnd = new javax.swing.JLabel();
        txtSemEnd = new javax.swing.JTextField();
        btnGenerateTestimonial = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Testimonial Generating System - Generate a Testimonial");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kyuLogo.png"))); // NOI18N

        jLabelSystemName.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelSystemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSystemName.setText("TESTIMONIAL GENERATING SYSTEM");
        jLabelSystemName.setToolTipText("TGS");

        jLabelInstructions.setText("Type the details as required to add the user.");

        jLabelRegno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRegno.setText("Registration number :");

        txtRegNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelCourseCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCourseCode.setText("Course Code :");

        txtCourseCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelYrOfEntry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelYrOfEntry.setText("Year of Entry :");

        txtYrOfEntry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelYrsTitle.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabelYrsTitle.setText("Get results up to:");

        jLabelYrStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelYrStart.setText("Year  (1, 2 or 3) : ");

        txtYrStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelSemEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSemEnd.setText("Semester (1 or 2) :");

        txtSemEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGenerateTestimonial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGenerateTestimonial.setText("Generate Testimonial");
        btnGenerateTestimonial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTestimonialActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSystemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYrsTitle)
                    .addComponent(jLabelInstructions)
                    .addComponent(jLabelRegno)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelCourseCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelYrOfEntry, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelYrStart))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYrStart, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYrOfEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnGenerateTestimonial)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtSemEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelSemEnd))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelLogo)
                .addGap(18, 18, 18)
                .addComponent(jLabelSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInstructions)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourseCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYrOfEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYrOfEntry))
                .addGap(18, 18, 18)
                .addComponent(jLabelYrsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYrStart)
                    .addComponent(txtYrStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSemEnd)
                    .addComponent(txtSemEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateTestimonial, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void btnGenerateTestimonialActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnGenerateTestimonialActionPerformed
        String RegNo = txtRegNo.getText();
        String CourseCode = (txtCourseCode.getText()).toUpperCase();
        String YrOfEntry = txtYrOfEntry.getText();
        String EndYr = txtYrStart.getText();
        String EndSem = txtSemEnd.getText();
        String Database = CourseCode + YrOfEntry;
        String sqlQueryCSD = "select * from CompSciDept where CourseCode=?";
        String sqlQueryDB = "select * from " + Database + " where RegNo='" + RegNo + "'";

        Font bold = new Font();
        bold.setStyle("bold");
        Font bold28 = new Font();
        bold28.setStyle("bold");
        bold28.setSize(28);
        Font size8 = new Font();
        size8.setSize(8);
        Font italic18 = new Font();
        italic18.setStyle("italic");
        italic18.setSize(18);

        try {
            PreparedStatement psCSD = conn.prepareStatement(sqlQueryCSD);
            PreparedStatement psDB = conn.prepareStatement(sqlQueryDB);
            psCSD.setString(1, CourseCode);
            ResultSet rsCSD = psCSD.executeQuery();
            ResultSet rsDB = psDB.executeQuery();

            rsCSD.next();
            rsDB.next();

            OutputStream file = new FileOutputStream(new File("D:\\TGS results\\"
                    + Database + "\\" + (rsDB.getString(1) + "_"
                    + rsDB.getString(2) + "_" + rsDB.getString(3)) + ".pdf"));
            Document document = new Document();
            PdfWriter.getInstance(document, file);

            PdfPTable table = new PdfPTable(3);
            table.setWidthPercentage(100);
            float[] columnWidths = {3f, 1f, 3f};
            table.setWidths(columnWidths);
            Paragraph KY = new Paragraph("KYAMBOGO", bold28);
            PdfPCell KYU1 = new PdfPCell(KY);
            Image image = Image.getInstance("/Users/rwothoromo/apps/general/TGS/src/images/kyulogoEdit.jpg");
            PdfPCell img = new PdfPCell(image, true);
            Paragraph U = new Paragraph("UNIVERSITY", bold28);
            PdfPCell KYU2 = new PdfPCell(U);
            KYU1.setVerticalAlignment(Element.ALIGN_BOTTOM);
            img.setVerticalAlignment(Element.ALIGN_MIDDLE);
            KYU2.setVerticalAlignment(Element.ALIGN_BOTTOM);
            KYU1.setHorizontalAlignment(Element.ALIGN_RIGHT);
            img.setHorizontalAlignment(Element.ALIGN_CENTER);
            KYU2.setHorizontalAlignment(Element.ALIGN_LEFT);
            KYU1.setBorder(Rectangle.NO_BORDER);
            img.setBorder(Rectangle.NO_BORDER);
            KYU2.setBorder(Rectangle.NO_BORDER);

            Paragraph Contacts = new Paragraph("P.O. BOX 1 KYAMBOGO\n"
                    + "Tel: 256-414-287347, 285001/2, Fax: 256-414-288492\n"
                    + "E-mail:deansci@kyu.ac.ug, www.kyu.ac.ug\n", size8);
            Contacts.setAlignment(Element.ALIGN_CENTER);
            Paragraph DEAN = new Paragraph("Office of the Dean, Faculty of Science", italic18);
            DEAN.setAlignment(Element.ALIGN_CENTER);
            Paragraph testimonial = new Paragraph("PARTIAL TESTIMONIAL\n\n", bold);
            testimonial.setAlignment(Element.ALIGN_CENTER);

            Date now = new Date();
            SimpleDateFormat fmt = new SimpleDateFormat("dd MMMM, yyyy");
            String date = fmt.format(now);

            document.open();
            document.add(table);
            Add3cells(document, table, KYU1, img, KYU2);
            document.add(Contacts);
            document.add(DEAN);
            document.add(new Paragraph("______________________________________________________________________________\n\n\n", bold));
            document.add(testimonial);
            document.add(new Paragraph("Date                     :      " + date, bold));
            document.add(new Paragraph("Name                   :      " + rsDB.getString(2) + " " + rsDB.getString(3), bold));
            document.add(new Paragraph("Registration No. :      " + rsDB.getString(4), bold));
            document.add(new Paragraph("Programme         :      " + rsCSD.getString(2), bold));
            document.add(new Paragraph("Duration              :      " + rsDB.getString(6) + " years", bold));
            document.add(new Paragraph("Year of Entry       :      " + rsDB.getString(7), bold));
            document.add(new Paragraph("Year of Exit         :      " + rsDB.getString(8), bold));
            document.add(new Paragraph("\n\n"));

            PdfPTable a = new PdfPTable(3); // 3 columns
            float[] a_columnWidths = {7f, 1f, 1f};
            a.setWidths(a_columnWidths);
            PdfPCell a1 = new PdfPCell(new Paragraph("Course Units and grades:", bold));
            PdfPCell a2 = new PdfPCell(new Paragraph("GP", bold));
            PdfPCell a3 = new PdfPCell(new Paragraph("  Grade", bold));
            Add3cells(document, a, a1, a2, a3);

            if ("1".equals(EndYr) && "1".equals(EndSem)) {
                do11(CourseCode, Database, RegNo, document, rsDB, bold);
                String sqlcmt11 = "select * from " + (Database + "_1_1") + " where RegNo='" + RegNo + "'";
                PreparedStatement pscmt11 = conn.prepareStatement(sqlcmt11);
                ResultSet cmt11 = pscmt11.executeQuery();
                cmt11.next();
                Phrase Remark = new Phrase();
                Remark.add(new Chunk("\nHe/She is on "));
                Remark.add(new Chunk((Comment(cmt11.getString("REMARKS"))), bold));
                Remark.add(new Chunk("These are the provisional Results."));
                document.add(new Paragraph(Remark));
            } else if ("1".equals(EndYr) && "2".equals(EndSem)) {
                do11(CourseCode, Database, RegNo, document, rsDB, bold);
                do12(CourseCode, Database, RegNo, document, rsDB, bold);
                String sqlcmt12 = "select * from " + (Database + "_1_2") + " where RegNo='" + RegNo + "'";
                PreparedStatement pscmt12 = conn.prepareStatement(sqlcmt12);
                ResultSet cmt12 = pscmt12.executeQuery();
                cmt12.next();
                Phrase Remark = new Phrase();
                Remark.add(new Chunk("\nHe/She is on "));
                Remark.add(new Chunk((Comment(cmt12.getString("REMARKS"))), bold));
                Remark.add(new Chunk("These are the provisional Results."));
                document.add(new Paragraph(Remark));
            } else if ("2".equals(EndYr) && "1".equals(EndSem)) {
                do11(CourseCode, Database, RegNo, document, rsDB, bold);
                do12(CourseCode, Database, RegNo, document, rsDB, bold);
                do21(CourseCode, Database, RegNo, document, rsDB, bold);
                String sqlcmt21 = "select * from " + (Database + "_2_1") + " where RegNo='" + RegNo + "'";
                PreparedStatement pscmt21 = conn.prepareStatement(sqlcmt21);
                ResultSet cmt21 = pscmt21.executeQuery();
                cmt21.next();
                Phrase Remark = new Phrase();
                Remark.add(new Chunk("\nHe/She is on "));
                Remark.add(new Chunk((Comment(cmt21.getString("REMARKS"))), bold));
                Remark.add(new Chunk("These are the provisional Results."));
                document.add(new Paragraph(Remark));
            } else if ("2".equals(EndYr) && "2".equals(EndSem)) {
                do11(CourseCode, Database, RegNo, document, rsDB, bold);
                do12(CourseCode, Database, RegNo, document, rsDB, bold);
                do21(CourseCode, Database, RegNo, document, rsDB, bold);
                do22(CourseCode, Database, RegNo, document, rsDB, bold);
                String sqlcmt22 = "select * from " + (Database + "_2_2") + " where RegNo='" + RegNo + "'";
                PreparedStatement pscmt22 = conn.prepareStatement(sqlcmt22);
                ResultSet cmt22 = pscmt22.executeQuery();
                cmt22.next();
                Phrase Remark = new Phrase();
                Remark.add(new Chunk("\nHe/She is on "));
                Remark.add(new Chunk((Comment(cmt22.getString("REMARKS"))), bold));
                Remark.add(new Chunk("These are the provisional Results."));
                document.add(new Paragraph(Remark));
            } else if ("3".equals(EndYr) && "1".equals(EndSem)) {
                do11(CourseCode, Database, RegNo, document, rsDB, bold);
                do12(CourseCode, Database, RegNo, document, rsDB, bold);
                do21(CourseCode, Database, RegNo, document, rsDB, bold);
                do22(CourseCode, Database, RegNo, document, rsDB, bold);
                do31(CourseCode, Database, RegNo, document, rsDB, bold);
                String sqlcmt31 = "select * from " + (Database + "_3_1") + " where RegNo='" + RegNo + "'";
                PreparedStatement pscmt31 = conn.prepareStatement(sqlcmt31);
                ResultSet cmt31 = pscmt31.executeQuery();
                cmt31.next();
                Phrase Remark = new Phrase();
                Remark.add(new Chunk("\nHe/She is on "));
                Remark.add(new Chunk((Comment(cmt31.getString("REMARKS"))), bold));
                Remark.add(new Chunk("These are the provisional Results."));
                document.add(new Paragraph(Remark));
            } else if ("3".equals(EndYr) && "2".equals(EndSem)) {
                do11(CourseCode, Database, RegNo, document, rsDB, bold);
                do12(CourseCode, Database, RegNo, document, rsDB, bold);
                do21(CourseCode, Database, RegNo, document, rsDB, bold);
                do22(CourseCode, Database, RegNo, document, rsDB, bold);
                do31(CourseCode, Database, RegNo, document, rsDB, bold);
                do32(CourseCode, Database, RegNo, document, rsDB, bold);
                String sqlcmt32 = "select * from " + (Database + "_3_2") + " where RegNo='" + RegNo + "'";
                PreparedStatement pscmt32 = conn.prepareStatement(sqlcmt32);
                ResultSet cmt32 = pscmt32.executeQuery();
                cmt32.next();
                Phrase Remark = new Phrase();
                Remark.add(new Chunk("\nHe/She is on "));
                Remark.add(new Chunk((Comment(cmt32.getString("REMARKS"))), bold));
                document.add(new Paragraph(Remark));
            }

            document.add(new Paragraph("Any assistance rendered to him/her will be highly appreciated."
                    + "\n\n\n\n\n\n\nAssoc. Prof. G. W. Byarugaba-Bazirake                         "
                    + "Date...................................................."));
            document.add(new Paragraph("DEAN", bold));
            document.close();
            file.close();
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "
                    + "D:\\TGS results\\" + Database + "\\"
                    + (rsDB.getString(1) + "_" + rsDB.getString(2)
                    + "_" + rsDB.getString(3)) + ".pdf");
            //Pops the generated pdf
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnGenerateTestimonialActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    public void do11(String CourseCode, String Database, String RegNo, Document document, ResultSet rsDB, Font bold) throws SQLException, DocumentException {
        String sqlQueryDB11 = "select * from " + (Database + "_1_1") + " where RegNo='" + RegNo + "'";
        PreparedStatement psDB11 = conn.prepareStatement(sqlQueryDB11);
        ResultSet rsDB11 = psDB11.executeQuery();
        rsDB11.next();

        PdfPTable b = new PdfPTable(1);
        b.setWidthPercentage(100);
        PdfPCell b1 = new PdfPCell(new Paragraph(rsDB.getString(7)
                + "/" + (Integer.parseInt(rsDB.getString(7)) + 1)
                + " Year One Semester One\n", bold));
        b.addCell(b1);
        document.add(b);

        if ("BITC".equals(CourseCode)) {
            BITC11(document, rsDB11, bold);
        } else if ("BIS".equals(CourseCode)) {
            BIS11(document, rsDB11, bold);
        } else if ("DCS".equals(CourseCode)) {
            DCS11(document, rsDB11, bold);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid details!");
        }

        PdfPTable c = new PdfPTable(1);
        c.setWidthPercentage(100);
        PdfPCell c1 = new PdfPCell(new Paragraph("\n"));
        c.addCell(c1);
        document.add(c);
    }

    public void do12(String CourseCode, String Database, String RegNo, Document document, ResultSet rsDB, Font bold) throws SQLException, DocumentException {
        String sqlQueryDB12 = "select * from " + (Database + "_1_2") + " where RegNo='" + RegNo + "'";
        PreparedStatement psDB12 = conn.prepareStatement(sqlQueryDB12);
        ResultSet rsDB12 = psDB12.executeQuery();
        rsDB12.next();

        PdfPTable d = new PdfPTable(1);
        d.setWidthPercentage(100);
        PdfPCell d1 = new PdfPCell(new Paragraph(rsDB.getString(7)
                + "/" + (Integer.parseInt(rsDB.getString(7)) + 1)
                + " Year One Semester Two\n", bold));
        d.addCell(d1);
        document.add(d);

        if ("BITC".equals(CourseCode)) {
            BITC12(document, rsDB12, bold);
        } else if ("BIS".equals(CourseCode)) {
            BIS12(document, rsDB12, bold);
        } else if ("DCS".equals(CourseCode)) {
            DCS12(document, rsDB12, bold);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Details!");
        }

        PdfPTable e = new PdfPTable(1);
        e.setWidthPercentage(100);
        PdfPCell e1 = new PdfPCell(new Paragraph("\n"));
        e.addCell(e1);
        document.add(e);
    }

    public void do21(String CourseCode, String Database, String RegNo, Document document, ResultSet rsDB, Font bold) throws SQLException, DocumentException {
        String sqlQueryDB21 = "select * from " + (Database + "_2_1") + " where RegNo='" + RegNo + "'";
        PreparedStatement psDB21 = conn.prepareStatement(sqlQueryDB21);
        ResultSet rsDB21 = psDB21.executeQuery();
        rsDB21.next();

        PdfPTable f = new PdfPTable(1);
        f.setWidthPercentage(100);
        PdfPCell f1 = new PdfPCell(new Paragraph(rsDB.getString(7)
                + "/" + (Integer.parseInt(rsDB.getString(7)) + 1)
                + " Year Two Semester One\n", bold));
        f.addCell(f1);
        document.add(f);

        if ("BITC".equals(CourseCode)) {
            BITC21(document, rsDB21, bold);
        } else if ("BIS".equals(CourseCode)) {
            BIS21(document, rsDB21, bold);
        } else if ("DCS".equals(CourseCode)) {
            DCS21(document, rsDB21, bold);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Details!");
        }

        PdfPTable g = new PdfPTable(1);
        g.setWidthPercentage(100);
        PdfPCell g1 = new PdfPCell(new Paragraph("\n"));
        g.addCell(g1);
        document.add(g);
    }

    public void do22(String CourseCode, String Database, String RegNo, Document document, ResultSet rsDB, Font bold) throws SQLException, DocumentException {
        String sqlQueryDB22 = "select * from " + (Database + "_2_2") + " where RegNo='" + RegNo + "'";
        PreparedStatement psDB22 = conn.prepareStatement(sqlQueryDB22);
        ResultSet rsDB22 = psDB22.executeQuery();
        rsDB22.next();

        PdfPTable d = new PdfPTable(1);
        d.setWidthPercentage(100);
        PdfPCell d1 = new PdfPCell(new Paragraph(rsDB.getString(7)
                + "/" + (Integer.parseInt(rsDB.getString(7)) + 1)
                + " Year One Semester Two\n", bold));
        d.addCell(d1);
        document.add(d);

        if ("BITC".equals(CourseCode)) {
            BITC22(document, rsDB22, bold);
        } else if ("BIS".equals(CourseCode)) {
            BIS22(document, rsDB22, bold);
        } else if ("DCS".equals(CourseCode)) {
            DCS22(document, rsDB22, bold);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Details!");
        }

        PdfPTable e = new PdfPTable(1);
        e.setWidthPercentage(100);
        PdfPCell e1 = new PdfPCell(new Paragraph("\n"));
        e.addCell(e1);
        document.add(e);
    }

    public void do31(String CourseCode, String Database, String RegNo, Document document, ResultSet rsDB, Font bold) throws SQLException, DocumentException {
        String sqlQueryDB31 = "select * from " + (Database + "_3_1") + " where RegNo='" + RegNo + "'";
        PreparedStatement psDB31 = conn.prepareStatement(sqlQueryDB31);
        ResultSet rsDB31 = psDB31.executeQuery();
        rsDB31.next();

        PdfPTable f = new PdfPTable(1);
        f.setWidthPercentage(100);
        PdfPCell f1 = new PdfPCell(new Paragraph(rsDB.getString(7)
                + "/" + (Integer.parseInt(rsDB.getString(7)) + 1)
                + " Year Two Semester One\n", bold));
        f.addCell(f1);
        document.add(f);

        if ("BITC".equals(CourseCode)) {
            BITC31(document, rsDB31, bold);
        } else if ("BIS".equals(CourseCode)) {
            BIS31(document, rsDB31, bold);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Details!");
        }

        PdfPTable g = new PdfPTable(1);
        g.setWidthPercentage(100);
        PdfPCell g1 = new PdfPCell(new Paragraph("\n"));
        g.addCell(g1);
        document.add(g);
    }

    public void do32(String CourseCode, String Database, String RegNo, Document document, ResultSet rsDB, Font bold) throws SQLException, DocumentException {
        String sqlQueryDB32 = "select * from " + (Database + "_3_2") + " where RegNo='" + RegNo + "'";
        PreparedStatement psDB32 = conn.prepareStatement(sqlQueryDB32);
        ResultSet rsDB32 = psDB32.executeQuery();
        rsDB32.next();

        PdfPTable d = new PdfPTable(1);
        d.setWidthPercentage(100);
        PdfPCell d1 = new PdfPCell(new Paragraph(rsDB.getString(7)
                + "/" + (Integer.parseInt(rsDB.getString(7)) + 1)
                + " Year One Semester Two\n", bold));
        d.addCell(d1);
        document.add(d);

        if ("BITC".equals(CourseCode)) {
            BITC32(document, rsDB32, bold);
        } else if ("BIS".equals(CourseCode)) {
            BIS32(document, rsDB32, bold);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Details!");
        }

        PdfPTable e = new PdfPTable(1);
        e.setWidthPercentage(100);
        PdfPCell e1 = new PdfPCell(new Paragraph("\n"));
        e.addCell(e1);
        document.add(e);
    }

    public void BITC11(Document document, ResultSet rsDB11, Font bold) throws DocumentException, SQLException {
        PdfPTable IT111 = new PdfPTable(3);
        float[] IT111_columnWidths = {7f, 1f, 1f};
        IT111.setWidths(IT111_columnWidths);
        PdfPCell IT111a = new PdfPCell(new Paragraph("IT 111 Introduction to Information Technology & Computing"));
        PdfPCell IT111b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(8)))));
        PdfPCell IT111c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(8))));
        Add3cells(document, IT111, IT111a, IT111b, IT111c);

        PdfPTable IT112 = new PdfPTable(3);
        float[] IT112_columnWidths = {7f, 1f, 1f};
        IT112.setWidths(IT112_columnWidths);
        PdfPCell IT112a = new PdfPCell(new Paragraph("IT 112 Micro-Computer Applications"));
        PdfPCell IT112b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(11)))));
        PdfPCell IT112c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(11))));
        Add3cells(document, IT112, IT112a, IT112b, IT112c);

        PdfPTable IT113 = new PdfPTable(3);
        float[] IT113_columnWidths = {7f, 1f, 1f};
        IT113.setWidths(IT113_columnWidths);
        PdfPCell IT113a = new PdfPCell(new Paragraph("IT 113 Discrete Mathematical Structures"));
        PdfPCell IT113b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(14)))));
        PdfPCell IT113c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(14))));
        Add3cells(document, IT113, IT113a, IT113b, IT113c);

        PdfPTable IT114 = new PdfPTable(3);
        float[] IT114_columnWidths = {7f, 1f, 1f};
        IT114.setWidths(IT114_columnWidths);
        PdfPCell IT114a = new PdfPCell(new Paragraph("IT 114 Probability & Statistics"));
        PdfPCell IT114b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(17)))));
        PdfPCell IT114c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(17))));
        Add3cells(document, IT114, IT114a, IT114b, IT114c);

        PdfPTable IT115 = new PdfPTable(3);
        float[] IT115_columnWidths = {7f, 1f, 1f};
        IT115.setWidths(IT115_columnWidths);
        PdfPCell IT115a = new PdfPCell(new Paragraph("IT 115 Differential, Integral & Vector Calculus"));
        PdfPCell IT115b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(20)))));
        PdfPCell IT115c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(20))));
        Add3cells(document, IT115, IT115a, IT115b, IT115c);

        PdfPTable HM111 = new PdfPTable(3);
        float[] HM111_columnWidths = {7f, 1f, 1f};
        HM111.setWidths(HM111_columnWidths);
        PdfPCell HM111a = new PdfPCell(new Paragraph("HM 111 Humanities & Communication Skills"));
        PdfPCell HM111b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(5)))));
        PdfPCell HM111c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(5))));
        Add3cells(document, HM111, HM111a, HM111b, HM111c);

        PdfPTable GPA11 = new PdfPTable(1);
        GPA11.setWidthPercentage(100);
        PdfPCell GPA11a = new PdfPCell(new Paragraph("GPA : " + rsDB11.getString(24), bold));
        GPA11.addCell(GPA11a);
        document.add(GPA11);
    }

    public void BIS11(Document document, ResultSet rsDB11, Font bold) throws DocumentException, SQLException {
        PdfPTable SIS1101 = new PdfPTable(3);
        float[] SIS1101_columnWidths = {7f, 1f, 1f};
        SIS1101.setWidths(SIS1101_columnWidths);
        PdfPCell SIS1101a = new PdfPCell(new Paragraph("SIS1 101 Introduction to Computers & Information Systems"));
        PdfPCell SIS1101b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(8)))));
        PdfPCell SIS1101c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(8))));
        Add3cells(document, SIS1101, SIS1101a, SIS1101b, SIS1101c);

        PdfPTable SIS1102 = new PdfPTable(3);
        float[] SIS1102_columnWidths = {7f, 1f, 1f};
        SIS1102.setWidths(SIS1102_columnWidths);
        PdfPCell SIS1102a = new PdfPCell(new Paragraph("SIS1 102 Computer Applications"));
        PdfPCell SIS1102b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(11)))));
        PdfPCell SIS1102c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(11))));
        Add3cells(document, SIS1102, SIS1102a, SIS1102b, SIS1102c);

        PdfPTable SIS1103 = new PdfPTable(3);
        float[] SIS1103_columnWidths = {7f, 1f, 1f};
        SIS1103.setWidths(SIS1103_columnWidths);
        PdfPCell SIS1103a = new PdfPCell(new Paragraph("SIS1 103 Business Statistics"));
        PdfPCell SIS1103b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(14)))));
        PdfPCell SIS1103c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(14))));
        Add3cells(document, SIS1103, SIS1103a, SIS1103b, SIS1103c);

        PdfPTable SIS1104 = new PdfPTable(3);
        float[] SIS1104_columnWidths = {7f, 1f, 1f};
        SIS1104.setWidths(SIS1104_columnWidths);
        PdfPCell SIS1104a = new PdfPCell(new Paragraph("SIS1 104 Discrete Mathematics"));
        PdfPCell SIS1104b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(17)))));
        PdfPCell SIS1104c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(17))));
        Add3cells(document, SIS1104, SIS1104a, SIS1104b, SIS1104c);

        PdfPTable SHM1101 = new PdfPTable(3);
        float[] SHM1101_columnWidths = {7f, 1f, 1f};
        SHM1101.setWidths(SHM1101_columnWidths);
        PdfPCell SHM1101a = new PdfPCell(new Paragraph("SHM1 101 Humanities & Communication Skills"));
        PdfPCell SHM1101b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(5)))));
        PdfPCell SHM1101c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(5))));
        Add3cells(document, SHM1101, SHM1101a, SHM1101b, SHM1101c);

        PdfPTable GPA11 = new PdfPTable(1);
        GPA11.setWidthPercentage(100);
        PdfPCell GPA11a = new PdfPCell(new Paragraph("GPA : " + rsDB11.getString(21), bold));
        GPA11.addCell(GPA11a);
        document.add(GPA11);
    }

    public void DCS11(Document document, ResultSet rsDB11, Font bold) throws DocumentException, SQLException {
        PdfPTable DCS111 = new PdfPTable(3);
        float[] DCS111_columnWidths = {7f, 1f, 1f};
        DCS111.setWidths(DCS111_columnWidths);
        PdfPCell DCS111a = new PdfPCell(new Paragraph("DCS 111 Introduction to Computer science"));
        PdfPCell DCS111b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(8)))));
        PdfPCell DCS111c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(8))));
        Add3cells(document, DCS111, DCS111a, DCS111b, DCS111c);

        PdfPTable DCS112 = new PdfPTable(3);
        float[] DCS112_columnWidths = {7f, 1f, 1f};
        DCS112.setWidths(DCS112_columnWidths);
        PdfPCell DCS112a = new PdfPCell(new Paragraph("DCS 112 Computer Science Mathematics - Introduction"));
        PdfPCell DCS112b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(11)))));
        PdfPCell DCS112c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(11))));
        Add3cells(document, DCS112, DCS112a, DCS112b, DCS112c);

        PdfPTable DCS113 = new PdfPTable(3);
        float[] DCS113_columnWidths = {7f, 1f, 1f};
        DCS113.setWidths(DCS113_columnWidths);
        PdfPCell DCS113a = new PdfPCell(new Paragraph("DCS 113 Computer applications"));
        PdfPCell DCS113b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(14)))));
        PdfPCell DCS113c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(14))));
        Add3cells(document, DCS113, DCS113a, DCS113b, DCS113c);

        PdfPTable DCS114 = new PdfPTable(3);
        float[] DCS114_columnWidths = {7f, 1f, 1f};
        DCS114.setWidths(DCS114_columnWidths);
        PdfPCell DCS114a = new PdfPCell(new Paragraph("DCS 114 Computer Architecture"));
        PdfPCell DCS114b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(17)))));
        PdfPCell DCS114c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(17))));
        Add3cells(document, DCS114, DCS114a, DCS114b, DCS114c);

        PdfPTable HM111 = new PdfPTable(3);
        float[] HM111_columnWidths = {7f, 1f, 1f};
        HM111.setWidths(HM111_columnWidths);
        PdfPCell HM111a = new PdfPCell(new Paragraph("HM 111 Humanities & Communication Skills"));
        PdfPCell HM111b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB11.getString(5)))));
        PdfPCell HM111c = new PdfPCell(new Paragraph(GPtoGrade(rsDB11.getString(5))));
        Add3cells(document, HM111, HM111a, HM111b, HM111c);

        PdfPTable GPA11 = new PdfPTable(1);
        GPA11.setWidthPercentage(100);
        PdfPCell GPA11a = new PdfPCell(new Paragraph("GPA : " + rsDB11.getString(21), bold));
        GPA11.addCell(GPA11a);
        document.add(GPA11);
    }

    public void BITC12(Document document, ResultSet rsDB12, Font bold) throws DocumentException, SQLException {
        PdfPTable IT121 = new PdfPTable(3);
        float[] IT121_columnWidths = {7f, 1f, 1f};
        IT121.setWidths(IT121_columnWidths);
        PdfPCell IT121a = new PdfPCell(new Paragraph("IT 121 Differential Equations"));
        PdfPCell IT121b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(5)))));
        PdfPCell IT121c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(5))));
        Add3cells(document, IT121, IT121a, IT121b, IT121c);

        PdfPTable IT122 = new PdfPTable(3);
        float[] IT122_columnWidths = {7f, 1f, 1f};
        IT122.setWidths(IT122_columnWidths);
        PdfPCell IT122a = new PdfPCell(new Paragraph("IT 122 Programming Language Fundamentals"));
        PdfPCell IT122b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(8)))));
        PdfPCell IT122c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(8))));
        Add3cells(document, IT122, IT122a, IT122b, IT122c);

        PdfPTable IT123 = new PdfPTable(3);
        float[] IT123_columnWidths = {7f, 1f, 1f};
        IT123.setWidths(IT123_columnWidths);
        PdfPCell IT123a = new PdfPCell(new Paragraph("IT 123 Linear Algebra"));
        PdfPCell IT123b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(11)))));
        PdfPCell IT123c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(11))));
        Add3cells(document, IT123, IT123a, IT123b, IT123c);

        PdfPTable IT124 = new PdfPTable(3);
        float[] IT124_columnWidths = {7f, 1f, 1f};
        IT124.setWidths(IT124_columnWidths);
        PdfPCell IT124a = new PdfPCell(new Paragraph("IT 124 Computer Architecture"));
        PdfPCell IT124b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(14)))));
        PdfPCell IT124c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(14))));
        Add3cells(document, IT124, IT124a, IT124b, IT124c);

        PdfPTable IT125 = new PdfPTable(3);
        float[] IT125_columnWidths = {7f, 1f, 1f};
        IT125.setWidths(IT125_columnWidths);
        PdfPCell IT125a = new PdfPCell(new Paragraph("IT 125 Operating System Concepts"));
        PdfPCell IT125b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(17)))));
        PdfPCell IT125c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(17))));
        Add3cells(document, IT125, IT125a, IT125b, IT125c);

        PdfPTable IT126 = new PdfPTable(3);
        float[] IT126_columnWidths = {7f, 1f, 1f};
        IT126.setWidths(IT126_columnWidths);
        PdfPCell IT126a = new PdfPCell(new Paragraph("IT 126 Computer Management & Maintenance"));
        PdfPCell IT126b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(20)))));
        PdfPCell IT126c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(20))));
        Add3cells(document, IT126, IT126a, IT126b, IT126c);

        PdfPTable GPA12 = new PdfPTable(2);
        GPA12.setWidthPercentage(100);
        PdfPCell GPA12a = new PdfPCell(new Paragraph("GPA : " + rsDB12.getString(24), bold));
        GPA12.addCell(GPA12a);
        PdfPCell GPA12b = new PdfPCell(new Paragraph("CGPA : " + rsDB12.getString(30), bold));
        GPA12.addCell(GPA12b);
        document.add(GPA12);
    }

    public void BIS12(Document document, ResultSet rsDB12, Font bold) throws DocumentException, SQLException {
        PdfPTable SIS1201 = new PdfPTable(3);
        float[] SIS1201_columnWidths = {7f, 1f, 1f};
        SIS1201.setWidths(SIS1201_columnWidths);
        PdfPCell SIS1201a = new PdfPCell(new Paragraph("SIS1 201 Management Information Systems"));
        PdfPCell SIS1201b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(5)))));
        PdfPCell SIS1201c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(5))));
        Add3cells(document, SIS1201, SIS1201a, SIS1201b, SIS1201c);

        PdfPTable SIS1202 = new PdfPTable(3);
        float[] SIS1202_columnWidths = {7f, 1f, 1f};
        SIS1202.setWidths(SIS1202_columnWidths);
        PdfPCell SIS1202a = new PdfPCell(new Paragraph("SIS1 202 Introduction to Programming"));
        PdfPCell SIS1202b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(8)))));
        PdfPCell SIS1202c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(8))));
        Add3cells(document, SIS1202, SIS1202a, SIS1202b, SIS1202c);

        PdfPTable SIS1203 = new PdfPTable(3);
        float[] SIS1203_columnWidths = {7f, 1f, 1f};
        SIS1203.setWidths(SIS1203_columnWidths);
        PdfPCell SIS1203a = new PdfPCell(new Paragraph("SIS1 203 Business Computing"));
        PdfPCell SIS1203b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(11)))));
        PdfPCell SIS1203c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(11))));
        Add3cells(document, SIS1203, SIS1203a, SIS1203b, SIS1203c);

        PdfPTable SIS1204 = new PdfPTable(3);
        float[] SIS1204_columnWidths = {7f, 1f, 1f};
        SIS1204.setWidths(SIS1204_columnWidths);
        PdfPCell SIS1204a = new PdfPCell(new Paragraph("SIS1 204 Computer Maintenance & management"));
        PdfPCell SIS1204b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(14)))));
        PdfPCell SIS1204c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(14))));
        Add3cells(document, SIS1204, SIS1204a, SIS1204b, SIS1204c);

        PdfPTable SIS1205 = new PdfPTable(3);
        float[] SIS1205_columnWidths = {7f, 1f, 1f};
        SIS1205.setWidths(SIS1205_columnWidths);
        PdfPCell SIS1205a = new PdfPCell(new Paragraph("SIS1 205 Internet Technologies & Webpage Authoring"));
        PdfPCell SIS1205b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(17)))));
        PdfPCell SIS1205c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(17))));
        Add3cells(document, SIS1205, SIS1205a, SIS1205b, SIS1205c);

        PdfPTable SIA1206 = new PdfPTable(3);
        float[] SIA1206_columnWidths = {7f, 1f, 1f};
        SIA1206.setWidths(SIA1206_columnWidths);
        PdfPCell SIA1206a = new PdfPCell(new Paragraph("SIA1 206 Industrial Attachment I"));
        PdfPCell SIA1206b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(20)))));
        PdfPCell SIA1206c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(20))));
        Add3cells(document, SIA1206, SIA1206a, SIA1206b, SIA1206c);

        PdfPTable GPA12 = new PdfPTable(2);
        GPA12.setWidthPercentage(100);
        PdfPCell GPA12a = new PdfPCell(new Paragraph("GPA : " + rsDB12.getString(24), bold));
        GPA12.addCell(GPA12a);
        PdfPCell GPA12b = new PdfPCell(new Paragraph("CGPA : " + rsDB12.getString(30), bold));
        GPA12.addCell(GPA12b);
        document.add(GPA12);
    }

    public void DCS12(Document document, ResultSet rsDB12, Font bold) throws DocumentException, SQLException {
        PdfPTable DCS121 = new PdfPTable(3);
        float[] DCS121_columnWidths = {7f, 1f, 1f};
        DCS121.setWidths(DCS121_columnWidths);
        PdfPCell DCS121a = new PdfPCell(new Paragraph("DCS 121 Management Information Systems"));
        PdfPCell DCS121b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(5)))));
        PdfPCell DCS121c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(5))));
        Add3cells(document, DCS121, DCS121a, DCS121b, DCS121c);

        PdfPTable DCS122 = new PdfPTable(3);
        float[] DCS122_columnWidths = {7f, 1f, 1f};
        DCS122.setWidths(DCS122_columnWidths);
        PdfPCell DCS122a = new PdfPCell(new Paragraph("DCS 122 Mathematics - Intermediate"));
        PdfPCell DCS122b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(8)))));
        PdfPCell DCS122c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(8))));
        Add3cells(document, DCS122, DCS122a, DCS122b, DCS122c);

        PdfPTable DCS123 = new PdfPTable(3);
        float[] DCS123_columnWidths = {7f, 1f, 1f};
        DCS123.setWidths(DCS123_columnWidths);
        PdfPCell DCS123a = new PdfPCell(new Paragraph("DCS 123 Database Management Systems - Introduction"));
        PdfPCell DCS123b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(11)))));
        PdfPCell DCS123c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(11))));
        Add3cells(document, DCS123, DCS123a, DCS123b, DCS123c);

        PdfPTable DCS124 = new PdfPTable(3);
        float[] DCS124_columnWidths = {7f, 1f, 1f};
        DCS124.setWidths(DCS124_columnWidths);
        PdfPCell DCS124a = new PdfPCell(new Paragraph("DCS 124 Programming & Programming Methodology - Introduction"));
        PdfPCell DCS124b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(14)))));
        PdfPCell DCS124c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(14))));
        Add3cells(document, DCS124, DCS124a, DCS124b, DCS124c);

        PdfPTable DCS125 = new PdfPTable(3);
        float[] DCS125_columnWidths = {7f, 1f, 1f};
        DCS125.setWidths(DCS125_columnWidths);
        PdfPCell DCS125a = new PdfPCell(new Paragraph("DCS 125 Systems Analysis & Design"));
        PdfPCell DCS125b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(17)))));
        PdfPCell DCS125c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(17))));
        Add3cells(document, DCS125, DCS125a, DCS125b, DCS125c);

        PdfPTable DCS126 = new PdfPTable(3);
        float[] DCS126_columnWidths = {7f, 1f, 1f};
        DCS126.setWidths(DCS126_columnWidths);
        PdfPCell DCS126a = new PdfPCell(new Paragraph("DCS 126 Industrial Attachment"));
        PdfPCell DCS126b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB12.getString(20)))));
        PdfPCell DCS126c = new PdfPCell(new Paragraph(GPtoGrade(rsDB12.getString(20))));
        Add3cells(document, DCS126, DCS126a, DCS126b, DCS126c);

        PdfPTable GPA12 = new PdfPTable(2);
        GPA12.setWidthPercentage(100);
        PdfPCell GPA12a = new PdfPCell(new Paragraph("GPA : " + rsDB12.getString(24), bold));
        GPA12.addCell(GPA12a);
        PdfPCell GPA12b = new PdfPCell(new Paragraph("CGPA : " + rsDB12.getString(30), bold));
        GPA12.addCell(GPA12b);
        document.add(GPA12);
    }

    public void BITC21(Document document, ResultSet rsDB21, Font bold) throws DocumentException, SQLException {
        PdfPTable IT211 = new PdfPTable(3);
        float[] IT211_columnWidths = {7f, 1f, 1f};
        IT211.setWidths(IT211_columnWidths);
        PdfPCell IT211a = new PdfPCell(new Paragraph("IT 211 Information Systems & Design"));
        PdfPCell IT211b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(5)))));
        PdfPCell IT211c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(5))));
        Add3cells(document, IT211, IT211a, IT211b, IT211c);

        PdfPTable IT212 = new PdfPTable(3);
        float[] IT212_columnWidths = {7f, 1f, 1f};
        IT212.setWidths(IT212_columnWidths);
        PdfPCell IT212a = new PdfPCell(new Paragraph("IT 212 Numerical Analysis & Computation"));
        PdfPCell IT212b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(8)))));
        PdfPCell IT212c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(8))));
        Add3cells(document, IT212, IT212a, IT212b, IT212c);

        PdfPTable IT213 = new PdfPTable(3);
        float[] IT213_columnWidths = {7f, 1f, 1f};
        IT213.setWidths(IT213_columnWidths);
        PdfPCell IT213a = new PdfPCell(new Paragraph("IT 213 Data Communication & Networking I"));
        PdfPCell IT213b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(11)))));
        PdfPCell IT213c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(11))));
        Add3cells(document, IT213, IT213a, IT213b, IT213c);

        PdfPTable IT214 = new PdfPTable(3);
        float[] IT214_columnWidths = {7f, 1f, 1f};
        IT214.setWidths(IT214_columnWidths);
        PdfPCell IT214a = new PdfPCell(new Paragraph("IT 214 Programming & Programming Methodology"));
        PdfPCell IT214b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(14)))));
        PdfPCell IT214c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(14))));
        Add3cells(document, IT214, IT214a, IT214b, IT214c);

        PdfPTable IT215 = new PdfPTable(3);
        float[] IT215_columnWidths = {7f, 1f, 1f};
        IT215.setWidths(IT215_columnWidths);
        PdfPCell IT215a = new PdfPCell(new Paragraph("IT 215 Data Structures & Algorithms"));
        PdfPCell IT215b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(17)))));
        PdfPCell IT215c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(17))));
        Add3cells(document, IT215, IT215a, IT215b, IT215c);

        PdfPTable GPA21 = new PdfPTable(1);
        GPA21.setWidthPercentage(100);
        PdfPCell GPA21a = new PdfPCell(new Paragraph("GPA : " + rsDB21.getString(21), bold));
        GPA21.addCell(GPA21a);
        PdfPCell GPA21b = new PdfPCell(new Paragraph("GPA : " + rsDB21.getString(27), bold));
        GPA21.addCell(GPA21b);
        document.add(GPA21);
    }

    public void BIS21(Document document, ResultSet rsDB21, Font bold) throws DocumentException, SQLException {
        PdfPTable SIS2101 = new PdfPTable(3);
        float[] SIS2101_columnWidths = {7f, 1f, 1f};
        SIS2101.setWidths(SIS2101_columnWidths);
        PdfPCell SIS2101a = new PdfPCell(new Paragraph("SIS2 101 E-Commerce"));
        PdfPCell SIS2101b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(5)))));
        PdfPCell SIS2101c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(5))));
        Add3cells(document, SIS2101, SIS2101a, SIS2101b, SIS2101c);

        PdfPTable SIS2102 = new PdfPTable(3);
        float[] SIS2102_columnWidths = {7f, 1f, 1f};
        SIS2102.setWidths(SIS2102_columnWidths);
        PdfPCell SIS2102a = new PdfPCell(new Paragraph("SIS2 102 Information Systems Analysis & Design"));
        PdfPCell SIS2102b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(8)))));
        PdfPCell SIS2102c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(8))));
        Add3cells(document, SIS2102, SIS2102a, SIS2102b, SIS2102c);

        PdfPTable SIS2103 = new PdfPTable(3);
        float[] SIS2103_columnWidths = {7f, 1f, 1f};
        SIS2103.setWidths(SIS2103_columnWidths);
        PdfPCell SIS2103a = new PdfPCell(new Paragraph("SIS2 103 Database Systems Design & Development"));
        PdfPCell SIS2103b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(11)))));
        PdfPCell SIS2103c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(11))));
        Add3cells(document, SIS2103, SIS2103a, SIS2103b, SIS2103c);

        PdfPTable SIS2104 = new PdfPTable(3);
        float[] SIS2104_columnWidths = {7f, 1f, 1f};
        SIS2104.setWidths(SIS2104_columnWidths);
        PdfPCell SIS2104a = new PdfPCell(new Paragraph("SIS2 104 Object-oriented Programming"));
        PdfPCell SIS2104b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(14)))));
        PdfPCell SIS2104c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(14))));
        Add3cells(document, SIS2104, SIS2104a, SIS2104b, SIS2104c);

        PdfPTable SHM2105 = new PdfPTable(3);
        float[] SHM2105_columnWidths = {7f, 1f, 1f};
        SHM2105.setWidths(SHM2105_columnWidths);
        PdfPCell SHM2105a = new PdfPCell(new Paragraph("SHM2 105 Multimedia systems"));
        PdfPCell SHM2105b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(17)))));
        PdfPCell SHM2105c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(17))));
        Add3cells(document, SHM2105, SHM2105a, SHM2105b, SHM2105c);

        PdfPTable GPA21 = new PdfPTable(1);
        GPA21.setWidthPercentage(100);
        PdfPCell GPA21a = new PdfPCell(new Paragraph("GPA : " + rsDB21.getString(21), bold));
        GPA21.addCell(GPA21a);
        PdfPCell GPA21b = new PdfPCell(new Paragraph("GPA : " + rsDB21.getString(27), bold));
        GPA21.addCell(GPA21b);
        document.add(GPA21);
    }

    public void DCS21(Document document, ResultSet rsDB21, Font bold) throws DocumentException, SQLException {
        PdfPTable DCS211 = new PdfPTable(3);
        float[] DCS211_columnWidths = {7f, 1f, 1f};
        DCS211.setWidths(DCS211_columnWidths);
        PdfPCell DCS211a = new PdfPCell(new Paragraph("DCS 211 Introduction to Operating Systems Concepts"));
        PdfPCell DCS211b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(8)))));
        PdfPCell DCS211c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(8))));
        Add3cells(document, DCS211, DCS211a, DCS211b, DCS211c);

        PdfPTable DCS212 = new PdfPTable(3);
        float[] DCS212_columnWidths = {7f, 1f, 1f};
        DCS212.setWidths(DCS212_columnWidths);
        PdfPCell DCS212a = new PdfPCell(new Paragraph("DCS 212 Database Management Systems - Intermediate"));
        PdfPCell DCS212b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(11)))));
        PdfPCell DCS212c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(11))));
        Add3cells(document, DCS212, DCS212a, DCS212b, DCS212c);

        PdfPTable DCS213 = new PdfPTable(3);
        float[] DCS213_columnWidths = {7f, 1f, 1f};
        DCS213.setWidths(DCS213_columnWidths);
        PdfPCell DCS213a = new PdfPCell(new Paragraph("DCS 213 Programming & Programming Methodology - Intermediate"));
        PdfPCell DCS213b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(14)))));
        PdfPCell DCS213c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(14))));
        Add3cells(document, DCS213, DCS213a, DCS213b, DCS213c);

        PdfPTable DCS214 = new PdfPTable(3);
        float[] DCS214_columnWidths = {7f, 1f, 1f};
        DCS214.setWidths(DCS214_columnWidths);
        PdfPCell DCS214a = new PdfPCell(new Paragraph("DCS 214 Operating Systems Implementation (UNIX/NT)"));
        PdfPCell DCS214b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(17)))));
        PdfPCell DCS214c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(17))));
        Add3cells(document, DCS214, DCS214a, DCS214b, DCS214c);

        PdfPTable DCS215 = new PdfPTable(3);
        float[] DCS215_columnWidths = {7f, 1f, 1f};
        DCS215.setWidths(DCS215_columnWidths);
        PdfPCell DCS215a = new PdfPCell(new Paragraph("DCS 215 Research Methodology"));
        PdfPCell DCS215b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(17)))));
        PdfPCell DCS215c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(20))));
        Add3cells(document, DCS215, DCS215a, DCS215b, DCS215c);

        PdfPTable HM211 = new PdfPTable(3);
        float[] HM211_columnWidths = {7f, 1f, 1f};
        HM211.setWidths(HM211_columnWidths);
        PdfPCell HM211a = new PdfPCell(new Paragraph("HM 211 Entrepreneurship Skills"));
        PdfPCell HM211b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB21.getString(5)))));
        PdfPCell HM211c = new PdfPCell(new Paragraph(GPtoGrade(rsDB21.getString(5))));
        Add3cells(document, HM211, HM211a, HM211b, HM211c);

        PdfPTable GPA21 = new PdfPTable(1);
        GPA21.setWidthPercentage(100);
        PdfPCell GPA21a = new PdfPCell(new Paragraph("GPA : " + rsDB21.getString(24), bold));
        GPA21.addCell(GPA21a);
        PdfPCell GPA21b = new PdfPCell(new Paragraph("GPA : " + rsDB21.getString(30), bold));
        GPA21.addCell(GPA21b);
        document.add(GPA21);
    }

    public void BITC22(Document document, ResultSet rsDB22, Font bold) throws DocumentException, SQLException {
        PdfPTable IT221 = new PdfPTable(3);
        float[] IT221_columnWidths = {7f, 1f, 1f};
        IT221.setWidths(IT221_columnWidths);
        PdfPCell IT221a = new PdfPCell(new Paragraph("IT 221 Operating System Implementation"));
        PdfPCell IT221b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(5)))));
        PdfPCell IT221c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(5))));
        Add3cells(document, IT221, IT221a, IT221b, IT221c);

        PdfPTable IT222 = new PdfPTable(3);
        float[] IT222_columnWidths = {7f, 1f, 1f};
        IT222.setWidths(IT222_columnWidths);
        PdfPCell IT222a = new PdfPCell(new Paragraph("IT 222 Programming & Programming Methodology II"));
        PdfPCell IT222b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(8)))));
        PdfPCell IT222c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(8))));
        Add3cells(document, IT222, IT222a, IT222b, IT222c);

        PdfPTable IT223 = new PdfPTable(3);
        float[] IT223_columnWidths = {7f, 1f, 1f};
        IT223.setWidths(IT223_columnWidths);
        PdfPCell IT223a = new PdfPCell(new Paragraph("IT 223 Database Management Systems"));
        PdfPCell IT223b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(11)))));
        PdfPCell IT223c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(11))));
        Add3cells(document, IT223, IT223a, IT223b, IT223c);

        PdfPTable IT224 = new PdfPTable(3);
        float[] IT224_columnWidths = {7f, 1f, 1f};
        IT224.setWidths(IT224_columnWidths);
        PdfPCell IT224a = new PdfPCell(new Paragraph("IT 224 Software Engineering"));
        PdfPCell IT224b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(14)))));
        PdfPCell IT224c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(14))));
        Add3cells(document, IT224, IT224a, IT224b, IT224c);

        PdfPTable IT225 = new PdfPTable(3);
        float[] IT225_columnWidths = {7f, 1f, 1f};
        IT225.setWidths(IT225_columnWidths);
        PdfPCell IT225a = new PdfPCell(new Paragraph("IT 225 Internet Technologies"));
        PdfPCell IT225b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(17)))));
        PdfPCell IT225c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(17))));
        Add3cells(document, IT225, IT225a, IT225b, IT225c);

        PdfPTable GPA22 = new PdfPTable(2);
        GPA22.setWidthPercentage(100);
        PdfPCell GPA22a = new PdfPCell(new Paragraph("GPA : " + rsDB22.getString(21), bold));
        GPA22.addCell(GPA22a);
        PdfPCell GPA22b = new PdfPCell(new Paragraph("CGPA : " + rsDB22.getString(27), bold));
        GPA22.addCell(GPA22b);
        document.add(GPA22);
    }

    public void BIS22(Document document, ResultSet rsDB22, Font bold) throws DocumentException, SQLException {
        PdfPTable SIS2201 = new PdfPTable(3);
        float[] SIS2201_columnWidths = {7f, 1f, 1f};
        SIS2201.setWidths(SIS2201_columnWidths);
        PdfPCell SIS2201a = new PdfPCell(new Paragraph("SIS2 201 Computer Networks & Data communications"));
        PdfPCell SIS2201b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(5)))));
        PdfPCell SIS2201c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(5))));
        Add3cells(document, SIS2201, SIS2201a, SIS2201b, SIS2201c);

        PdfPTable SIS2202 = new PdfPTable(3);
        float[] SIS2202_columnWidths = {7f, 1f, 1f};
        SIS2202.setWidths(SIS2202_columnWidths);
        PdfPCell SIS2202a = new PdfPCell(new Paragraph("SIS2 202 Website Design, Programming & Administration"));
        PdfPCell SIS2202b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(8)))));
        PdfPCell SIS2202c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(8))));
        Add3cells(document, SIS2202, SIS2202a, SIS2202b, SIS2202c);

        PdfPTable SIS2203 = new PdfPTable(3);
        float[] SIS2203_columnWidths = {7f, 1f, 1f};
        SIS2203.setWidths(SIS2203_columnWidths);
        PdfPCell SIS2203a = new PdfPCell(new Paragraph("SIS2 203 Database Systems Implementation"));
        PdfPCell SIS2203b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(11)))));
        PdfPCell SIS2203c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(11))));
        Add3cells(document, SIS2203, SIS2203a, SIS2203b, SIS2203c);

        PdfPTable SIS2204 = new PdfPTable(3);
        float[] SIS2204_columnWidths = {7f, 1f, 1f};
        SIS2204.setWidths(SIS2204_columnWidths);
        PdfPCell SIS2204a = new PdfPCell(new Paragraph("SIS2 204 Research Methods"));
        PdfPCell SIS2204b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(14)))));
        PdfPCell SIS2204c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(14))));
        Add3cells(document, SIS2204, SIS2204a, SIS2204b, SIS2204c);

        PdfPTable SIS2205 = new PdfPTable(3);
        float[] SIS2205_columnWidths = {7f, 1f, 1f};
        SIS2205.setWidths(SIS2205_columnWidths);
        PdfPCell SIS2205a = new PdfPCell(new Paragraph("SIS2 205 Business Process Analysis and Modeling"));
        PdfPCell SIS2205b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(17)))));
        PdfPCell SIS2205c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(17))));
        Add3cells(document, SIS2205, SIS2205a, SIS2205b, SIS2205c);

        PdfPTable SIS2206 = new PdfPTable(3);
        float[] SIS2206_columnWidths = {7f, 1f, 1f};
        SIS2206.setWidths(SIS2206_columnWidths);
        PdfPCell SIS2206a = new PdfPCell(new Paragraph("SIA2 206 Industrial Attachment II"));
        PdfPCell SIS2206b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(20)))));
        PdfPCell SIS2206c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(20))));
        Add3cells(document, SIS2206, SIS2206a, SIS2206b, SIS2206c);

        PdfPTable GPA22 = new PdfPTable(2);
        GPA22.setWidthPercentage(100);
        PdfPCell GPA22a = new PdfPCell(new Paragraph("GPA : " + rsDB22.getString(24), bold));
        GPA22.addCell(GPA22a);
        PdfPCell GPA22b = new PdfPCell(new Paragraph("CGPA : " + rsDB22.getString(30), bold));
        GPA22.addCell(GPA22b);
        document.add(GPA22);
    }

    public void DCS22(Document document, ResultSet rsDB22, Font bold) throws DocumentException, SQLException {
        PdfPTable DCS221 = new PdfPTable(3);
        float[] DCS221_columnWidths = {7f, 1f, 1f};
        DCS221.setWidths(DCS221_columnWidths);
        PdfPCell DCS221a = new PdfPCell(new Paragraph("DCS 221 Computer Management & Maintenance"));
        PdfPCell DCS221b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(5)))));
        PdfPCell DCS221c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(5))));
        Add3cells(document, DCS221, DCS221a, DCS221b, DCS221c);

        PdfPTable DCS222 = new PdfPTable(3);
        float[] DCS222_columnWidths = {7f, 1f, 1f};
        DCS222.setWidths(DCS222_columnWidths);
        PdfPCell DCS222a = new PdfPCell(new Paragraph("DCS 222 Data Communications & Networking"));
        PdfPCell DCS222b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(8)))));
        PdfPCell DCS222c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(8))));
        Add3cells(document, DCS222, DCS222a, DCS222b, DCS222c);

        PdfPTable DCS223 = new PdfPTable(3);
        float[] DCS223_columnWidths = {7f, 1f, 1f};
        DCS223.setWidths(DCS223_columnWidths);
        PdfPCell DCS223a = new PdfPCell(new Paragraph("DCS 223 Visual Basic Programming"));
        PdfPCell DCS223b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(11)))));
        PdfPCell DCS223c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(11))));
        Add3cells(document, DCS223, DCS223a, DCS223b, DCS223c);

        PdfPTable DCS224 = new PdfPTable(3);
        float[] DCS224_columnWidths = {7f, 1f, 1f};
        DCS224.setWidths(DCS224_columnWidths);
        PdfPCell DCS224a = new PdfPCell(new Paragraph("DCS 224 Web Development Technology"));
        PdfPCell DCS224b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(14)))));
        PdfPCell DCS224c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(14))));
        Add3cells(document, DCS224, DCS224a, DCS224b, DCS224c);

        PdfPTable DCS228 = new PdfPTable(3);
        float[] DCS228_columnWidths = {7f, 1f, 1f};
        DCS228.setWidths(DCS228_columnWidths);
        PdfPCell DCS228a = new PdfPCell(new Paragraph("DCS 228 Project"));
        PdfPCell DCS228b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(17)))));
        PdfPCell DCS228c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(17))));
        Add3cells(document, DCS228, DCS228a, DCS228b, DCS228c);

        PdfPTable DCS226 = new PdfPTable(3);
        float[] DCS226_columnWidths = {7f, 1f, 1f};
        DCS226.setWidths(DCS226_columnWidths);
        PdfPCell DCS226a = new PdfPCell(new Paragraph("DCS 226 Industrial Attachment"));
        PdfPCell DCS226b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB22.getString(20)))));
        PdfPCell DCS226c = new PdfPCell(new Paragraph(GPtoGrade(rsDB22.getString(20))));
        Add3cells(document, DCS226, DCS226a, DCS226b, DCS226c);

        PdfPTable GPA22 = new PdfPTable(2);
        GPA22.setWidthPercentage(100);
        PdfPCell GPA22a = new PdfPCell(new Paragraph("GPA : " + rsDB22.getString(24), bold));
        GPA22.addCell(GPA22a);
        PdfPCell GPA22b = new PdfPCell(new Paragraph("CGPA : " + rsDB22.getString(30), bold));
        GPA22.addCell(GPA22b);
        document.add(GPA22);
    }

    public void BITC31(Document document, ResultSet rsDB31, Font bold) throws DocumentException, SQLException {
        PdfPTable IT311 = new PdfPTable(3);
        float[] IT311_columnWidths = {7f, 1f, 1f};
        IT311.setWidths(IT311_columnWidths);
        PdfPCell IT311a = new PdfPCell(new Paragraph("IT 311 Introduction to Graph Theory"));
        PdfPCell IT311b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(5)))));
        PdfPCell IT311c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(5))));
        Add3cells(document, IT311, IT311a, IT311b, IT311c);

        PdfPTable IT312 = new PdfPTable(3);
        float[] IT312_columnWidths = {7f, 1f, 1f};
        IT312.setWidths(IT312_columnWidths);
        PdfPCell IT312a = new PdfPCell(new Paragraph("IT 312 Network Management & Security"));
        PdfPCell IT312b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(8)))));
        PdfPCell IT312c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(8))));
        Add3cells(document, IT312, IT312a, IT312b, IT312c);

        PdfPTable IT313 = new PdfPTable(3);
        float[] IT313_columnWidths = {7f, 1f, 1f};
        IT313.setWidths(IT313_columnWidths);
        PdfPCell IT313a = new PdfPCell(new Paragraph("IT 313 Computer Graphics"));
        PdfPCell IT313b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(11)))));
        PdfPCell IT313c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(11))));
        Add3cells(document, IT313, IT313a, IT313b, IT313c);

        PdfPTable IT314 = new PdfPTable(3);
        float[] IT314_columnWidths = {7f, 1f, 1f};
        IT314.setWidths(IT314_columnWidths);
        PdfPCell IT314a = new PdfPCell(new Paragraph("IT 314 Distributed Computer Systems"));
        PdfPCell IT314b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(14)))));
        PdfPCell IT314c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(14))));
        Add3cells(document, IT314, IT314a, IT314b, IT314c);

        PdfPTable IT315 = new PdfPTable(3);
        float[] IT315_columnWidths = {7f, 1f, 1f};
        IT315.setWidths(IT315_columnWidths);
        PdfPCell IT315a = new PdfPCell(new Paragraph("IT 315 Data Communications & Networking II"));
        PdfPCell IT315b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(17)))));
        PdfPCell IT315c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(17))));
        Add3cells(document, IT315, IT315a, IT315b, IT315c);

        PdfPTable GPA31 = new PdfPTable(1);
        GPA31.setWidthPercentage(100);
        PdfPCell GPA31a = new PdfPCell(new Paragraph("GPA : " + rsDB31.getString(21), bold));
        GPA31.addCell(GPA31a);
        PdfPCell GPA31b = new PdfPCell(new Paragraph("GPA : " + rsDB31.getString(27), bold));
        GPA31.addCell(GPA31b);
        document.add(GPA31);
    }

    public void BIS31(Document document, ResultSet rsDB31, Font bold) throws DocumentException, SQLException {
        PdfPTable SIS3101 = new PdfPTable(3);
        float[] SIS3101_columnWidths = {7f, 1f, 1f};
        SIS3101.setWidths(SIS3101_columnWidths);
        PdfPCell SIS3101a = new PdfPCell(new Paragraph("SIS3 101 Systems Administration"));
        PdfPCell SIS3101b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(8)))));
        PdfPCell SIS3101c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(8))));
        Add3cells(document, SIS3101, SIS3101a, SIS3101b, SIS3101c);

        PdfPTable SIS3102 = new PdfPTable(3);
        float[] SIS3102_columnWidths = {7f, 1f, 1f};
        SIS3102.setWidths(SIS3102_columnWidths);
        PdfPCell SIS3102a = new PdfPCell(new Paragraph("SIS3 102 Information Systems Project Management"));
        PdfPCell SIS3102b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(11)))));
        PdfPCell SIS3102c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(11))));
        Add3cells(document, SIS3102, SIS3102a, SIS3102b, SIS3102c);

        PdfPTable SIS3103 = new PdfPTable(3);
        float[] SIS3103_columnWidths = {7f, 1f, 1f};
        SIS3103.setWidths(SIS3103_columnWidths);
        PdfPCell SIS3103a = new PdfPCell(new Paragraph("SIS3 103 Information Systems Security"));
        PdfPCell SIS3103b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(14)))));
        PdfPCell SIS3103c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(14))));
        Add3cells(document, SIS3103, SIS3103a, SIS3103b, SIS3103c);

        PdfPTable SIS3104 = new PdfPTable(3);
        float[] SIS3104_columnWidths = {7f, 1f, 1f};
        SIS3104.setWidths(SIS3104_columnWidths);
        PdfPCell SIS3104a = new PdfPCell(new Paragraph("SIS3 104 Software Engineering Principals"));
        PdfPCell SIS3104b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(17)))));
        PdfPCell SIS3104c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(17))));
        Add3cells(document, SIS3104, SIS3104a, SIS3104b, SIS3104c);

        PdfPTable SHM3101 = new PdfPTable(3);
        float[] SHM3101_columnWidths = {7f, 1f, 1f};
        SHM3101.setWidths(SHM3101_columnWidths);
        PdfPCell SHM3101a = new PdfPCell(new Paragraph("SHM3 101 Entrepreneurship Skills"));
        PdfPCell SHM3101b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB31.getString(5)))));
        PdfPCell SHM3101c = new PdfPCell(new Paragraph(GPtoGrade(rsDB31.getString(5))));
        Add3cells(document, SHM3101, SHM3101a, SHM3101b, SHM3101c);

        PdfPTable GPA31 = new PdfPTable(1);
        GPA31.setWidthPercentage(100);
        PdfPCell GPA31a = new PdfPCell(new Paragraph("GPA : " + rsDB31.getString(21), bold));
        GPA31.addCell(GPA31a);
        PdfPCell GPA31b = new PdfPCell(new Paragraph("GPA : " + rsDB31.getString(27), bold));
        GPA31.addCell(GPA31b);
        document.add(GPA31);
    }

    public void BITC32(Document document, ResultSet rsDB32, Font bold) throws DocumentException, SQLException {
        PdfPTable IT321 = new PdfPTable(3);
        float[] IT321_columnWidths = {7f, 1f, 1f};
        IT321.setWidths(IT321_columnWidths);
        PdfPCell IT321a = new PdfPCell(new Paragraph("IT 321 Oracle Database Management System"));
        PdfPCell IT321b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(5)))));
        PdfPCell IT321c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(5))));
        Add3cells(document, IT321, IT321a, IT321b, IT321c);

        PdfPTable IT322 = new PdfPTable(3);
        float[] IT322_columnWidths = {7f, 1f, 1f};
        IT322.setWidths(IT322_columnWidths);
        PdfPCell IT322a = new PdfPCell(new Paragraph("IT 322 Microprocessor Based Design"));
        PdfPCell IT322b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(8)))));
        PdfPCell IT322c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(8))));
        Add3cells(document, IT322, IT322a, IT322b, IT322c);

        PdfPTable IT323 = new PdfPTable(3);
        float[] IT323_columnWidths = {7f, 1f, 1f};
        IT323.setWidths(IT323_columnWidths);
        PdfPCell IT323a = new PdfPCell(new Paragraph("IT 323 Analysis & Design of Algorithms"));
        PdfPCell IT323b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(11)))));
        PdfPCell IT323c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(11))));
        Add3cells(document, IT323, IT323a, IT323b, IT323c);

        PdfPTable IT324 = new PdfPTable(3);
        float[] IT324_columnWidths = {7f, 1f, 1f};
        IT324.setWidths(IT324_columnWidths);
        PdfPCell IT324a = new PdfPCell(new Paragraph("IT 324 Geographic Information Systems & Processing"));
        PdfPCell IT324b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(14)))));
        PdfPCell IT324c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(14))));
        Add3cells(document, IT324, IT324a, IT324b, IT324c);

        PdfPTable IT325 = new PdfPTable(3);
        float[] IT325_columnWidths = {7f, 1f, 1f};
        IT325.setWidths(IT325_columnWidths);
        PdfPCell IT325a = new PdfPCell(new Paragraph("IT 325 Research Project Work"));
        PdfPCell IT325b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(17)))));
        PdfPCell IT325c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(17))));
        Add3cells(document, IT325, IT325a, IT325b, IT325c);

        PdfPTable GPA32 = new PdfPTable(2);
        GPA32.setWidthPercentage(100);
        PdfPCell GPA32a = new PdfPCell(new Paragraph("GPA : " + rsDB32.getString(21), bold));
        GPA32.addCell(GPA32a);
        PdfPCell GPA32b = new PdfPCell(new Paragraph("CGPA : " + rsDB32.getString(27), bold));
        GPA32.addCell(GPA32b);
        document.add(GPA32);
    }

    public void BIS32(Document document, ResultSet rsDB32, Font bold) throws DocumentException, SQLException {
        PdfPTable SIS3201 = new PdfPTable(3);
        float[] SIS3201_columnWidths = {7f, 1f, 1f};
        SIS3201.setWidths(SIS3201_columnWidths);
        PdfPCell SIS3201a = new PdfPCell(new Paragraph("SIS3 201 Decision Support Systems"));
        PdfPCell SIS3201b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(5)))));
        PdfPCell SIS3201c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(5))));
        Add3cells(document, SIS3201, SIS3201a, SIS3201b, SIS3201c);

        PdfPTable SIS3202 = new PdfPTable(3);
        float[] SIS3202_columnWidths = {7f, 1f, 1f};
        SIS3202.setWidths(SIS3202_columnWidths);
        PdfPCell SIS3202a = new PdfPCell(new Paragraph("SIS3 202 Social Issues in Computing"));
        PdfPCell SIS3202b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(8)))));
        PdfPCell SIS3202c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(8))));
        Add3cells(document, SIS3202, SIS3202a, SIS3202b, SIS3202c);

        PdfPTable SIS3203 = new PdfPTable(3);
        float[] SIS3203_columnWidths = {7f, 1f, 1f};
        SIS3203.setWidths(SIS3203_columnWidths);
        PdfPCell SIS3203a = new PdfPCell(new Paragraph("SIS3 203 Organizational Behaviour"));
        PdfPCell SIS3203b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(11)))));
        PdfPCell SIS3203c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(11))));
        Add3cells(document, SIS3203, SIS3203a, SIS3203b, SIS3203c);

        PdfPTable SIS3204 = new PdfPTable(3);
        float[] SIS3204_columnWidths = {7f, 1f, 1f};
        SIS3204.setWidths(SIS3204_columnWidths);
        PdfPCell SIS3204a = new PdfPCell(new Paragraph("SIS3 204 Business Intelligence & Data Warehousing"));
        PdfPCell SIS3204b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(14)))));
        PdfPCell SIS3204c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(14))));
        Add3cells(document, SIS3204, SIS3204a, SIS3204b, SIS3204c);

        PdfPTable SIS3205 = new PdfPTable(3);
        float[] SIS3205_columnWidths = {7f, 1f, 1f};
        SIS3205.setWidths(SIS3205_columnWidths);
        PdfPCell SIS3205a = new PdfPCell(new Paragraph("SIS3 205 BIS Project"));
        PdfPCell SIS3205b = new PdfPCell(new Paragraph(String.valueOf(Float.valueOf(rsDB32.getString(17)))));
        PdfPCell SIS3205c = new PdfPCell(new Paragraph(GPtoGrade(rsDB32.getString(17))));
        Add3cells(document, SIS3205, SIS3205a, SIS3205b, SIS3205c);

        PdfPTable GPA32 = new PdfPTable(2);
        GPA32.setWidthPercentage(100);
        PdfPCell GPA32a = new PdfPCell(new Paragraph("GPA : " + rsDB32.getString(21), bold));
        GPA32.addCell(GPA32a);
        PdfPCell GPA32b = new PdfPCell(new Paragraph("CGPA : " + rsDB32.getString(27), bold));
        GPA32.addCell(GPA32b);
        document.add(GPA32);
    }

    public String GPtoGrade(String conn) {
        if ("5".equals(conn)) {
            return "   A";
        }
        if ("4.5".equals(conn)) {
            return "   B+";
        }
        if ("4".equals(conn)) {
            return "   B";
        }
        if ("3.5".equals(conn)) {
            return "   B-";
        }
        if ("3".equals(conn)) {
            return "   C+";
        }
        if ("2.5".equals(conn)) {
            return "   C";
        }
        if ("2".equals(conn)) {
            return "   C-";
        }
        if ("1.5".equals(conn)) {
            return "   D+";
        }
        if ("1".equals(conn)) {
            return "   D";
        }
        if ("0.5".equals(conn)) {
            return "   D-";
        }
        if ("0".equals(conn)) {
            return "   E";
        }
        return conn;

    }

    public String Comment(String conn) {
        if ("NP(VCL)".equals(conn) || "NP (VCL)".equals(conn) || conn.contains("VCL")) {
            return "Vice Chancellor's List. ";
        } else if ("NP(DL)".equals(conn) || "NP (DL)".equals(conn) || (conn.contains("NP") && conn.contains("DL"))) {
            return "Normal Progress (Dean's List). ";
        } else if ("NP".equals(conn) || conn.contains("NP")) {
            return "Normal Progress. ";
        } else if ("PP".equals(conn) || conn.contains("PP") == true) {
            return "Probationary Progress. ";
        } else {
            return conn;
        }
    }

    public void Add3cells(Document conn, PdfPTable row, PdfPCell cellA, PdfPCell cellB, PdfPCell cellC) throws DocumentException {
        row.setWidthPercentage(100);
        cellB.setHorizontalAlignment(Element.ALIGN_CENTER);
        row.addCell(cellA);
        row.addCell(cellB);
        row.addCell(cellC);
        conn.add(row);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Processing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Processing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Processing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Processing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Processing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateTestimonial;
    private javax.swing.JLabel jLabelCourseCode;
    private javax.swing.JLabel jLabelInstructions;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelRegno;
    private javax.swing.JLabel jLabelSemEnd;
    private javax.swing.JLabel jLabelSystemName;
    private javax.swing.JLabel jLabelYrOfEntry;
    private javax.swing.JLabel jLabelYrStart;
    private javax.swing.JLabel jLabelYrsTitle;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtRegNo;
    private javax.swing.JTextField txtSemEnd;
    private javax.swing.JTextField txtYrOfEntry;
    private javax.swing.JTextField txtYrStart;
    // End of variables declaration//GEN-END:variables
}
